# Generated by Django 5.1.2 on 2024-11-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='menu_images/default_image.png', upload_to='img_upload/'),
        ),
    ]
