# Generated by Django 5.1.2 on 2024-11-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='dish_of_the_day',
            field=models.BooleanField(default=False),
        ),
    ]
